generator: admingenerator.generator.doctrine
params:
  model: TC\IndexBundle\Entity\Category
  namespace_prefix: TC
  bundle_name: IndexBundle
  fields: ~

builders:
  list:
    params:
      title: List for IndexBundle
      display: [title]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
        up: 
          label: Move up
        down: 
          label: Move down
  filters:
    params:
      display: [title]
  new:
    params:
      title: New object for IndexBundle
      display: [title, parent]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Category.title }}"
      display: [title, parent]
      actions:
        list: ~
  delete: ~
