generator: admingenerator.generator.doctrine
params:
  model: TC\IndexBundle\Entity\Category
  namespace_prefix: TC
  bundle_name: IndexBundle
  fields: 
    text:
      label: Texte affiché (HTML autorisé)
    title: 
      label: Titre
    path: 
      label: Chemin
  max_per_page: 50

builders:
  list:
    params:
      title: Liste des catégories
      display: [title, path]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: 
          confirm: Ceci supprimera tous les enfants, le cas échéant. 
        up: 
          label: Déplacer vers le haut
          route: tc_index_category_list_up
        down: 
          label: Déplacer vers le bas
          route: tc_index_category_list_up
  filters:
    params:  
      display: []
  new:
    params:
      title: Nouvelle catégorie
      display: [title, parent, text]
      actions:
        list: ~
  edit:
    params:
      title: Édition de la catégorie "{{ Category.title }}"
      display: [title, parent, text]
      actions:
        list: ~
  delete: ~
