generator: admingenerator.generator.doctrine
params:
  model: TC\IndexBundle\Entity\Item
  namespace_prefix: TC
  bundle_name: IndexBundle
  fields: 
    title: 
      label: Titre
    url:
      label: URL
    category: 
      label: Catégorie

builders:
  list:
    params:
      title: Liste des items
      display: [title, url, category]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [title, url, category]
  new:
    params:
      title: Nouvel item
      display: [title, url, synopsis, category]
      actions:
        list: ~
  edit:
    params:
      title: Édition de l'item "{{ Item.title }}"
      display: [title, url, synopsis, category]
      actions:
        list: ~
  delete: ~
