TCIndexBundle_homepage:
    pattern:  /
    defaults: { _controller: TCIndexBundle:Default:index }

admin_category:
    resource: "@TCIndexBundle/Controller/Category/"
    type:     admingenerator
    prefix:   /index/admin/category

admin_item:
    resource: "@TCIndexBundle/Controller/Item/"
    type:     admingenerator
    prefix:   /index/admin/item

category_mover_up:
    pattern:   /index/admin/category/{pk}/move-up
    defaults:  { _controller: TCIndexBundle:CategoryMover:up }

category_mover_down:
    pattern:   /index/admin/category/{pk}/move-down
    defaults:  { _controller: TCIndexBundle:CategoryMover:down }

index:
    resource: "@TCIndexBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

importer:
    resource: "@TCIndexBundle/Controller/ImporterController.php"
    type:     annotation
    prefix:   /index/admin/import

config:
    resource: "@TCIndexBundle/Controller/ConfigurationController.php"
    type:     annotation
    prefix:   /index/admin/configuration