TCIndexBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TCIndexBundle:Default:index }

admin_category:
    resource: "@TCIndexBundle/Controller/Category/"
    type:     admingenerator
    prefix:   /index/admin/category

category_mover_up:
    pattern:   /index/admin/category/{id}/move-up
    defaults:  { _controller: TCIndexBundle:CategoryMover:up }

category_mover_down:
    pattern:   /index/admin/category/{id}/move-down
    defaults:  { _controller: TCIndexBundle:CategoryMover:down }
