TCIndexBundle_homepage:
    pattern:  /
    defaults: { _controller: TCIndexBundle:Default:index }

admin_category:
    resource: "@TCIndexBundle/Controller/Category/"
    type:     admingenerator
    prefix:   /index/admin/category

admin_category_mover:
    resource: "@TCIndexBundle/Controller/Category/"
    type:     annotation
    prefix:   /index/admin/category

admin_item:
    resource: "@TCIndexBundle/Controller/Item/"
    type:     admingenerator
    prefix:   /index/admin/item

admin_user:
    resource: "@TCIndexBundle/Controller/User/"
    type:     admingenerator
    prefix:   /index/admin/user

admin_user_adminswitcher:
    resource: "@TCIndexBundle/Controller/User/"
    type:     annotation
    prefix:   /index/admin/user

index:
    resource: "@TCIndexBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

importer:
    resource: "@TCIndexBundle/Controller/ImporterController.php"
    type:     annotation
    prefix:   /index/admin/import

config:
    resource: "@TCIndexBundle/Controller/ConfigurationController.php"
    type:     annotation
    prefix:   /index/admin/configuration