TCIndexBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TCIndexBundle:Default:index }

admin_category:
    resource: "@TCIndexBundle/Controller/Category/"
    type:     admingenerator
    prefix:   /index/category