parameters:
#    tc_index.example.class: TC\IndexBundle\Example

services:
#    tc_index.example:
#        class: %tc_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tc_index.listener:
        class: TC\IndexBundle\Listeners\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }