parameters:
#    tc_index.example.class: TC\IndexBundle\Example

services:
#    tc_index.example:
#        class: %tc_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tc_index.listener:
        class: TC\IndexBundle\Listeners\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            
    twig.extension.gabarit:
        class: TC\IndexBundle\Twig\GabaritExtension
        arguments: [@doctrine] 
        tags:
            - { name: twig.extension }
            
    kernel.listener.dvp_authentication_listener: 
        class: TC\IndexBundle\Listeners\LoginFormPreAuthenticateListener
        arguments: [@doctrine.orm.entity_manager, @fos_user.user_manager, @security.encoder_factory, @fos_user.util.user_manipulator]
        tags: 
            - { name: kernel.event_listener, priority: 100, event: kernel.request, method: handle }