imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    esi:             { enabled: true }
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%
        charset:  UTF8

    orm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    
sensio_framework_extra:
    router:  { annotations: true }
    request: { converters:  true }
    view:    { annotations: true }
    cache:   { annotations: true }

jms_security_extra:
    expressions: true
    # secure_controllers:  true
    secure_all_services: false

jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop

knp_menu:
    twig: true

fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: TC\IndexBundle\Entity\User

admingenerator_generator:
    knp_menu_class: TC\IndexBundle\Menu\AdminMenu
    base_admin_template: TCIndexBundle:Default:_main.html.twig
    use_propel: false
    use_doctrine_orm: true
    use_doctrine_odm: false
    overwrite_if_exists: true

admingenerator_user:
    login_template: AdmingeneratorGeneratorBundle::base_login_assetic_less.html.twig
